[package]
name = "macro_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reflect = "0.0.13"

[[bin]]
name="main"
path="src/main.rs"

[[file]]
name="macros"
path="src/macros.rs"